<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Got it</name>
   <tag></tag>
   <elementGuidId>51599a09-af79-407e-a821-ca1d2b578235</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.cc-btn.cc-dismiss</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4d70a5a-9235-453e-bd73-14ccc23274be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>dismiss cookie message</value>
      <webElementGuid>bc617ea9-55dc-4800-8df1-ad8f7334cbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c660aeec-a109-4fdf-8a54-5df81c8e1e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>302ccd24-adb5-469d-9065-7991bcf16094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cc-btn cc-dismiss</value>
      <webElementGuid>567f134c-54d1-498d-97f3-e449f02d2b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Got it</value>
      <webElementGuid>8f3207a4-af73-4a83-af91-648a38c14cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;cc-window cc-banner cc-type-info cc-theme-block cc-bottom cc-color-override-2104694695&quot;]/div[@class=&quot;cc-compliance&quot;]/a[@class=&quot;cc-btn cc-dismiss&quot;]</value>
      <webElementGuid>a480596a-d029-4e36-b530-d922f439ac76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div/a</value>
      <webElementGuid>1b18264f-4f1b-470a-a1e4-862ff3103bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Got it')]</value>
      <webElementGuid>5136ea3f-89a5-4a3c-9526-31b4fbbb7292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Privacy Policy)'])[1]/following::a[1]</value>
      <webElementGuid>0fb5dd64-c938-4859-9f1c-05c6a5ad7dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Got it']/parent::*</value>
      <webElementGuid>100ac5ef-9c43-400a-ac90-63dcf06f235c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>6965d77f-603a-41df-bc5c-32f641005111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Got it' or . = 'Got it')]</value>
      <webElementGuid>942b3aee-3dd0-4b11-a5f2-f166e3582c93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
