<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_External user_EMailAddress</name>
   <tag></tag>
   <elementGuidId>445ffc56-9fef-48f8-b3ab-4328c5c7e5c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dx_dx-2caf73b8-bedb-3132-870a-db3b1bceeb14_EMailAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='devextreme0']/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80abf34d-4988-4400-853f-a32e8fa0f20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-email</value>
      <webElementGuid>80087cc8-59de-47a0-94b0-17044afaa41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dx_dx-2caf73b8-bedb-3132-870a-db3b1bceeb14_EMailAddress</value>
      <webElementGuid>13dcd424-bfbf-4249-81f6-3bbc4c7e92c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-texteditor-input</value>
      <webElementGuid>688193e2-e3f7-4d77-94db-50758135068e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>983becde-1e13-4cce-88ef-7c3a78e9949e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dfa813be-a1a1-40e9-9127-1916375109b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EMailAddress</value>
      <webElementGuid>3b2b5a28-9379-470d-b3fe-0423ad8ef4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>222b6fd3-43b8-4a63-80fb-b849e2c4f4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>51b21c3b-27f9-41c3-8c5a-d3ea93cafa13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b1d41de-9888-4e75-baf4-75802f60a2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dx_dx-2caf73b8-bedb-3132-870a-db3b1bceeb14_EMailAddress&quot;)</value>
      <webElementGuid>a7c925eb-2863-4bfe-b2a5-dcebc036f40c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dx_dx-2caf73b8-bedb-3132-870a-db3b1bceeb14_EMailAddress']</value>
      <webElementGuid>8fbbf8c1-71f8-44f2-9f7c-1e805008e65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='devextreme0']/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>a1985251-04f0-4400-9402-8f3db8af0e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>78cdda1a-6cbf-4e08-b600-da8e4aad27bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dx_dx-2caf73b8-bedb-3132-870a-db3b1bceeb14_EMailAddress' and @type = 'text' and @name = 'EMailAddress']</value>
      <webElementGuid>613b2999-3594-4f65-a9e7-7763487d54fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
