<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_External user_Password</name>
   <tag></tag>
   <elementGuidId>6a92fb02-ca0d-40b6-b44b-37750ef9a3be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dx_dx-75a21c29-af3b-e886-3687-474b5b396837_Password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='devextreme3']/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c84ef9a-708e-4a34-877d-831e1aadef78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>4e992a7b-c1d4-44bd-8d51-d83528b229bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dx_dx-75a21c29-af3b-e886-3687-474b5b396837_Password</value>
      <webElementGuid>eea424c3-757b-4b42-9403-1f27dd338b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-texteditor-input</value>
      <webElementGuid>b8184416-1296-459b-af1f-ffc510bc3065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e1d0b0da-b38a-4962-b380-1860d6c1fb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b78efb7a-fdb2-45f5-aed5-fbe15debd916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>97b42d0b-0cd1-4005-8dee-450ced4ec588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6752d673-7848-4e66-b78f-4faa0fd298a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>cc25fb9c-d082-427a-82a6-1f1f56ec056e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a12bfdf7-e060-4bd3-99b9-3849b9bb1923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dx_dx-75a21c29-af3b-e886-3687-474b5b396837_Password&quot;)</value>
      <webElementGuid>2f1a20f4-e303-4461-a1e4-d97c823a03ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dx_dx-75a21c29-af3b-e886-3687-474b5b396837_Password']</value>
      <webElementGuid>66605e1c-b91a-4c8f-b896-03426e5e256d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='devextreme3']/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>c9e4041d-a2a4-479f-a58a-7589b8b41c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>dc83797e-b63b-44fb-ab93-1b4f1d4526ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dx_dx-75a21c29-af3b-e886-3687-474b5b396837_Password' and @type = 'password' and @name = 'Password']</value>
      <webElementGuid>0963929b-7157-4ee5-8688-501f64c4f4f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
